#!/usr/bin/env bash
# -*- coding: utf-8 -*-

# General Formatting
#define GEN_FORMAT_RESET                "0"
#define GEN_FORMAT_BOLD                 "1"
#define GEN_FORMAT_DIM                  "2"
#define GEN_FORMAT_ITALIC               "3"
#define GEN_FORMAT_BLINK                "4"
#define GEN_FORMAT_REVERSE              "5"
#define GEN_FORMAT_HIDDEN               "6"

# Foreground Colors
#define FOREGROUND_COL_BLACK            "30"
#define FOREGROUND_COL_RED              "31"
#define FOREGROUND_COL_GREEN            "32"
#define FOREGROUND_COL_YELLOW           "33"
#define FOREGROUND_COL_BLUE             "34"
#define FOREGROUND_COL_MAGENTA          "35"
#define FOREGROUND_COL_CYAN             "36"
#define FOREGROUND_COL_WHITE            "37"

# Background Colors
#define BACKGROUND_COL_BLACK            "40"
#define BACKGROUND_COL_RED              "41"
#define BACKGROUND_COL_GREEN            "42"
#define BACKGROUND_COL_YELLOW           "43"
#define BACKGROUND_COL_BLUE             "44"
#define BACKGROUND_COL_MAGENTA          "45"
#define BACKGROUND_COL_CYAN             "46"
#define BACKGROUND_COL_WHITE            "47"

# Set Colors for Log Outputs
if perl -v >/dev/null 2>/dev/null; then
    RESET=$(perl -e 'print("\e[0m")')
    BOLD=$(perl -e 'print("\e[1m")')
    ITALIC=$(perl -e 'print("\e[3m")')
    FOREROUND_COLOR=$(perl -e 'print("\e[34m")')
    BACKGROUND_COLOR=$(perl -e 'print("\e[47m")')
elif python -V >/dev/null 2>/dev/null; then
    RESET=$(echo 'import sys; sys.stdout.write("\033[0m")' | python)
    BOLD=$(echo 'import sys; sys.stdout.write("\033[1m")' | python)
    ITALIC=$(echo 'import sys; sys.stdout.write("\033[3m")' | python)
    FOREROUND_COLOR=$(echo 'import sys; sys.stdout.write("\033[34m")' | python)
    BACKGROUND_COLOR=$(echo 'import sys; sys.stdout.write("\033[47m")' | python)
else
    RESET=
    ITALIC=
    BOLD=
    FOREROUND_COLOR=
    BACKGROUND_COLOR=
fi
