version: "3.7"

services:
  build:
    image: xcompany/xbuild:devcontainer
    build:
      context: ..
      dockerfile: Dockerfile.devcontainer

  unit:
    image: xcompany/xbuild:devcontainer
    depends_on:
      - build
    volumes:
      - ../tests/unit/:/workspace/tests/unit/:ro
    command: /usr/bin/bats /workspace/tests/unit/
