version: "3.7"

services:
  build:
    image: xcompany/xbuild:devcontainer
    build:
      context: ..
      dockerfile: Dockerfile

  unit:
    image: xcompany/xbuild:devcontainer
    depends_on:
      - build
    volumes:
      - ../:/workspace/
      - ../tests/unit:/tests
    command: /usr/local/bin/xb-test
