version: "3.7"

services:
  build:
    image: xcompany/xbuild:test
    build:
      context: ..
      dockerfile: Dockerfile

  unit:
    image: xcompany/xbuild:test
    depends_on:
      - build
    volumes:
      - ../tests/unit/:/tests/
      - ../src/xcompany/xbuild/build/:/build/
      - ./sources.list:/etc/xbuild/sources.list
      - ./xbuild.conf:/etc/xbuild/xbuild.conf
    command: /usr/local/bin/xb-test
