#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function build() {

    services=$(find /build/services/* -type d)
    for serviceDir in $services; do

        service=$(basename "$serviceDir")
        header "Build Service '$service'"

        buildFile="/build/services/$service/$service.build"
        if [ -f "$buildFile" ]; then
            log "Execute Service Build File"
            execute chmod 0755 "$buildFile"
            execute chown -R root:root "$buildFile"
            /bin/bash -l -c "$buildFile"
        fi
    done

    if [ -d "/build/fsroot" ]; then
        header "Copy File System Root Files"
        execute cp -rf /build/rootfs/* /
        execute rm -rf /build/README.md
    fi

    if [ -d "/build/events" ]; then

        for event in /build/events/*; do

            header "Copy Events ..."

            execute chown root:root "$event"
            execute chmod 0755 "$event"

            ext=${event##*\.}
            if [ "$ext" = "run" ]; then
                execute cp -rf "$event" /etc/cont-init.d
            fi

            if [ "$ext" = "finish" ]; then
                execute cp -rf "$event" /etc/cont-finish.d
            fi
        done
    fi

    for serviceDir in $services; do

        service=$(basename "$serviceDir")
        header "Configure Service '$service'"

        log "Prepare Service Home"
        local serviceHome="/etc/service.d/$service"

        if [ -d "$serviceHome" ]; then
            execute rm -rf "$serviceHome"
        fi

        execute mkdir -p "$serviceHome"

        if [ -f "/build/services/$service/$service.run" ]; then
            execute cp -f "/build/services/$service/$service.run" "$serviceHome/run"
            execute chmod 0755 "$serviceHome/run"
            execute chown root:root "$serviceHome/run"
        fi

        if [ -f "/build/services/$service/$service.finish" ]; then
            execute cp -f "/build/services/$service/$service.finish" "$serviceHome/finish"
            execute chmod 0755 "$serviceHome/finish"
            execute chown root:root "$serviceHome/finish"
        fi

        healthFile="/build/services/$service/$service.health"
        if [ -f "$healthFile" ]; then
            log "Copy Health Check Scripts"
            copy "$healthFile" "/etc/xinit/health.d/"
        fi

        log "Service '$service' successful installed."
    done
}
