#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function debug() {
    # Enable/Disable Debug Output

    args=("$@")
    local debugmode="0"
    local devmode="0"
    local silent="0"
    local reload="0"

    for arg in "${args[@]}"; do
        if [ "$arg" = "--on" ]; then
            debugmode="1"
        fi

        if [ "$arg" = "--dev" ]; then
            devmode="1"
        fi

        if [ "$arg" = "--reload" ]; then
            reload="1"
        fi

        if [ "$arg" = "--silent" ]; then
            silent="1"
        fi
    done

    if [ "$reload" = "1" ]; then
        if [ ! -z "$XBUILD_DEBUG" ]; then
            debugmode="$XBUILD_DEBUG"
        fi
    fi

    if [ "$devmode" = "1" ]; then
        set -eux -o pipefail
    else
        set -eu -o pipefail
    fi

    if [ "$silent" = "1" ]; then
        setvar "XBUILD_DEBUG" "$debugmode" --silent
    else
        setvar "XBUILD_DEBUG" "$debugmode"
    fi
}
