#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function execute() {

    # Execute an Command and print the Command to the Console
    local cmd="+ $@"
    echo "${FOREROUND_COLOR}${cmd}${RESET}"

    if [ ! -z "$XBUILD_DEBUG" ] && [ "$XBUILD_DEBUG" = 1 ]; then
        "$@" 2>&1
    else
        "$@" >/dev/null
    fi
}
