#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function printvars() {
    header "Print current Environment Variables"

    env -0 | while IFS='=' read -r -d '' env_name env_value; do
        log "$env_name=$env_value"
    done
}
