#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function build() {

    if [ -d "/build/fsroot" ]; then
        header "Copy File System Root Files"
        cp -Rf "/build/fsroot/*" /
    fi

    if [ -d "/build/events" ]; then

        for event in /build/events/*; do
            header "Copy Events ..."
            copy "$event" /etc/xinit/events.d
        done

        if [ -d "/build/events/post" ]; then

            for event in /build/events/post/*; do
                header "Copy Post Events ..."
                copy "$event" /etc/xinit/events.d/post.d
            done
        fi

        if [ -d "/build/events/prev" ]; then

            for event in /build/events/prev/*; do
                header "Copy Prev Events ..."
                copy "$event" /etc/xinit/events.d/prev.d
            done
        fi
    fi

    for service in /build/services/*; do

        header "Build Service '$service'"

        if [ -d "/build/services/$service/" ]; then
            log "Prepare Service Home"
            local serviceHome="/etc/sv/$service"
            local activeServiceHome="/etc/service/$service"
            if [ -d "$activeServiceHome" ]; then
                execute rm -rf "$activeServiceHome"
            fi

            if [ -d "$serviceHome" ]; then
                execute rm -rf "$serviceHome"
            fi
            execute mkdir -p "$serviceHome"

            copy "/build/services/$service/$service.run" "$serviceHome"
            execute chmod 0755 "$serviceHome/$service.run"
            execute chown -R root:root "$serviceHome/$service.run"

            if [ -f "/build/services/$service/$service.finish" ]; then
                copy "/build/services/$service/$service.finish" "$serviceHome"
                execute chmod 0755 "$serviceHome/$service.finish"
                execute chown -R root:root "$serviceHome/$service.finish"
            fi

            execute ln -s "$serviceHome" "$activeServiceHome"
        fi

        if [ -f "/build/services/$service/$service.health" ]; then
            log "Copy Health Check Scripts"
            copy "/build/services/$service/$service.health" "/etc/xinit/health.d/"
        fi

        buildFile="/build/services/$service/$service.build"
        if [ -f "$buildFile" ]; then
            log "Execute Service Build File"
            execute chmod 0755 "$buildFile"
            execute chown -R root:root "$buildFile"
            /usr/bin/bash -c "$buildFile"
        fi
    done
}
