#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function build() {

    if [ -d "/build/fsroot" ]; then
        header "Copy File System Root Files"
        execute cp -rf /build/fsroot/* /
        execute rm -rf /build/README.md
    fi

    if [ -d "/build/events" ]; then

        for event in /build/events/*; do

            if [ "$event" != "/build/events/post" ] && [ "$event" != "/build/events/prev" ]; then
                header "Copy Events ..."

                execute chown root:root "$event"
                execute chmod 0755 "$event"

                execute cp -rf "$event" /etc/xinit/events.d
            fi
        done

        if [ -d "/build/events/post" ]; then

            for event in /build/events/post/*; do
                header "Copy Post Events ..."

                execute chown root:root "$event"
                execute chmod 0755 "$event"

                execute cp -rf "$event" /etc/xinit/events.d/post.d
            done
        fi

        if [ -d "/build/events/prev" ]; then

            for event in /build/events/prev/*; do
                header "Copy Prev Events ..."

                execute chown root:root "$event"
                execute chmod 0755 "$event"

                execute cp -rf "$event" /etc/xinit/events.d/prev.d
            done
        fi
    fi

    services=$(find /build/services/* -type d)
    for serviceDir in $services; do

        service=$(basename "$serviceDir")
        header "Build Service '$service'"

        log "Prepare Service Home"
        local serviceHome="/etc/sv/$service"
        local activeServiceHome="/etc/service/$service"

        if [ -d "$serviceHome" ]; then
            execute rm -rf "$serviceHome"
        fi

        if [ -d "$activeServiceHome" ]; then
            execute rm -rf "$activeServiceHome"
        fi

        execute mkdir -p "$serviceHome"

        if [ -f "/build/services/$service/$service.run" ]; then
            execute cp -f "/build/services/$service/$service.run" "$serviceHome/run"
            execute chmod 0755 "$serviceHome/run"
            execute chown root:root "$serviceHome/run"
        fi

        if [ -f "/build/services/$service/$service.finish" ]; then
            execute cp -f "/build/services/$service/$service.finish" "$serviceHome/finish"
            execute chmod 0755 "$serviceHome/finish"
            execute chown root:root "$serviceHome/finish"
        fi

        execute ln -s "$serviceHome" "$activeServiceHome"

        healthFile="/build/services/$service/$service.health"
        if [ -f "$healthFile" ]; then
            log "Copy Health Check Scripts"
            copy "$healthFile" "/etc/xinit/health.d/"
        fi

        buildFile="/build/services/$service/$service.build"
        if [ -f "$buildFile" ]; then
            log "Execute Service Build File"
            execute chmod 0755 "$buildFile"
            execute chown -R root:root "$buildFile"
            /bin/bash -c "$buildFile"
        fi
    done
}
