#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function build()
{
    args=("$@")

    if [ -z "$args" ]
    then
        log "No Services given to build. Please call 'build --services <service1> <service2> ... <serviceN>'"
        return 1
    else
        for arg in "${args[@]}"
        do
            service=$arg

            if [ "$service" != "-s" ] && [ "$service" != "--services" ]
            then

                header "Build Service '$service'"

                if [ -d "/build/services/$service/runit/" ]
                then
                    log "Prepare Service Home"
                    local serviceHome="/etc/sv/$service"
                    local activeServiceHome="/etc/service/$service"
                    if [ -d "$activeServiceHome" ]
                    then
                        execute rm -rf "$activeServiceHome"
                    fi

                    if [ -d "$serviceHome" ]
                    then
                        execute rm -rf "$serviceHome"
                    fi
                    execute mkdir -p "$serviceHome"

                    for file in /build/services/$service/runit/*
                    do
                        copy "$file" $serviceHome

                        local onlyFileName=$(basename $file)

                        execute chmod 0755 "$serviceHome/$onlyFileName"
                        execute chown -R root:root "$serviceHome/$onlyFileName"
                        execute ln -s "$serviceHome" "$activeServiceHome"
                    done
                fi

                if [ -f "/build/services/$service/$service.health" ]
                then
                    log "Copy Health Check Scripts"
                    copy "/build/services/$service/$service.health" "/etc/xinit/health.d/"
                fi
            fi
        done
    fi
}
