#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function cleanup()
{
    # Cleans up the Image after an build.

    # Remove non-critical packages (don't remove busybox -> don't sure if this ist still a problem on debian 7)
    # ~i 					-> list all installed packages
    # !~M 					-> don't list automatic installed packages
    # !~prequired 			-> don't list packages with priority required
    # !~pimportant 			-> don't list packages with priority important
    # !~R~prequired 		-> don't list dependency packages of required packages
    # !~R~pimportant 		-> don't list dependency packages of important packages
    # !~R~R~prequired 		-> don't list dependency packages of dependency packages of required packages -.- (two levels should be enough. Have not found a recursive option)
    # !~R~R~pimportant 		-> ... required packages

    # !busybox 				-> don't list busybox
    # !grub 				-> don't list grub (we need a boot manager. If LILO or something else is used change this)
    # !initramfs-tools 		-> don't list initramfs-tools (else the kernel is gone)

    # System Packages
    # !runit-systemd
    # !cron
    # !syslog-ng-core
    # !logrotate
    # !locales
    # !apt-transport-https
    # !ca-certificates

    header "Cleanup Build"

    log "Remove non-critical packages"
    base_pattern="~i!~M!~prequired!~pimportant!~R~prequired!~R~R~prequired!~R~pimportant!~R~R~pimportant"

    # Keep System Packages
    system_packages="$base_pattern!busybox!grub!initramfs-tools!ca-certificates"

    # Keep installed User Packages
    excludes=$system_packages$(< /var/local/xbuild/packages.retain)

    packages_to_remove=( $(aptitude search "$excludes" --display-format "%p") )
    packages_to_remove+=( "$(< /var/local/xbuild/packages.remove)" )
    for package in "${packages_to_remove[@]}"
    do
        execute apt-get -qy purge "$package"
    done


    execute apt-get -qy purge aptitude
    execute apt-get -qy autoremove
    execute apt-get clean

    #find /.build/ -not \( -name '.build' -or -name 'buildconfig' -or -name 'cleanup.sh' \) -delete

    log "Cleanup the Temp Folder"
    execute rm -rf /tmp/* /var/tmp/*

    log "Remove cached Package Lists"
    execute rm -rf /var/lib/apt/lists/*

    log "Remove SSH Host keys"
    execute rm -f /etc/ssh/ssh_host_*

    header "Reconfigure Default Editor"
    log "Set vi as default editor"
    setvar "VISUAL" "vi"
    setvar "EDITOR" "vi"
}
