#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function hardening() {

    header "Hardening the Image"

    log "Remove existing crontabs, if any."
    exeucte rm -rf /var/spool/cron
    execute rm -rf /etc/crontabs
    execute rm -rf /etc/periodic

    log "Remove world-writable permissions."
    execute find / -xdev -type d -perm /0002 -exec chmod o-w {} +
    execute find / -xdev -type f -perm /0002 -exec chmod o-w {} +

    log "Assign write Access for all to tmp"
    execute chmod 1777 /tmp

    log "Remove unnecessary user accounts"
    execute sed -i -r '/^(user|root|_apt)/!d' /etc/group
    execute sed -i -r '/^(user|root|_apt)/!d' /etc/passwd

    log "Remove interactive login shell for everybody but user"
    execute sed -i -r '/^user:/! s#^(.*):[^:]*$#\1:/sbin/nologin#' /etc/passwd

    local sysdirs="
        /bin
        /etc
        /lib
        /sbin
        /usr
    "

    log "Remove crufty"
    # #   /etc/shadow-
    # #   /etc/passwd-
    # #   /etc/group-
    execute find $sysdirs -xdev -type f -regex '.*-$' -exec rm -f {} +

    log "Ensure system dirs are owned by root and not writable by anybody else"
    execute find $sysdirs -xdev -type d \
        -exec chown root:root {} \; \
        -exec chmod 0755 {} \;

    log "Remove all suid files"
    execute find $sysdirs -xdev -type f -and -perm /4000 -delete

    log "Remove init scripts since we do not use them"
    execute rm -rf /etc/init.d
    execute rm -rf /lib/rc
    execute rm -rf /etc/conf.d
    execute rm -rf /etc/inittab
    execute rm -rf /etc/runlevels
    execute rm -rf /etc/rc.conf

    log "Remove kernel tunables since we do not need them"
    execute rm -rf /etc/sysctl*
    execute rm -rf /etc/modprobe.d
    execute rm -rf /etc/modules
    execute rm -rf /etc/mdev.conf
    execute rm -rf /etc/acpi

    log "Remove root homedir since we do not need it"
    execute rm -fr /root

    log "Remove fstab since we do not need it."
    execute rm -f /etc/fstab

    log "Remove broken symlinks (because we removed the targets above)"
    execute find $sysdirs -xdev -type l -exec test ! -e {} \; -delete
}
