#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function header()
{
    local title="$1"
    echo ""
    echo "${BLUE_BG}${YELLOW}${BOLD}${title}${RESET}"
    echo "------------------------------------------"
}
