#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function header()
{
    local title="$1"
    echo ""
    echo "${BACKGROUND_COLOR}${FOREROUND_COLOR}${BOLD}${ITALIC}${title}${RESET}"
    echo "------------------------------------------"
}
