#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function install() {
    # Installs an Package with minimal effort

    args=("$@")
    local packages=""

    # This Packages will not saved. So it could later removed by cleanup
    excludes=("apt-utils" "software-properties-common" "psmisc" "wget" "dirmngr")

    # shellcheck disable=SC2128
    if [ -z "$args" ]; then
        log "No Packages given to install. Please call 'install --packages <package1> <package2> ... <packageN>'"
        return 1
    else
        for arg in "${args[@]}"; do
            if [ "$arg" != "-p" ] && [ "$arg" != "--packages" ]; then
                packages+="$arg "
                should_saved="true"

                for exclude in "${excludes[@]}"; do
                    if [ "$exclude" = "$arg" ]; then
                        should_saved="false"
                        {
                            echo "$arg"
                        } >>/var/local/xbuild/packages.remove
                    fi
                done

                if [ "$should_saved" = "true" ]; then
                    # Save the Package to remind it
                    {
                        echo -n "!$arg"
                    } >>/var/local/xbuild/packages.retain
                fi
            fi
        done

        log "Install Package(s) '$packages'"

        # shellcheck disable=SC2086
        execute apt-get install -qy --no-install-recommends $packages
    fi
}
