#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function savevars()
{
    header "Save all Environment Variables"

    # Excluded Vars from saving
    excludes=("HOME" "USER" "GROUP" "UID" "GID" "HOSTNAME" "PATH" "PWD" "SHLVL" "_")

    env -0 | while IFS='=' read -r -d '' env_name env_value
    do
        isExcluded="false"
        for exclude in "${excludes[@]}"
        do
            if [ "$env_name" = "$exclude" ]
            then
                isExcluded="true"
            fi
        done

        if [ "$isExcluded" == "false" ]
        then
            log "Save Environment Variable '$env_name'"
            echo "$env_value" > "/etc/xinit/env.d/$env_name"
        fi
    done
}
