#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function setvar()
{
    local env_name="$1"
    local env_value="$2"

    header "Set Environment Variable '$env_name' ..."

    echo "$env_value" > "/etc/xinit/env.d/$env_name"
    declare -x "$env_name=$env_value"
}
