#!/usr/bin/env bash
# -*- coding: utf-8 -*-

function setvar() {
    local env_name="$1"
    local env_value="$2"

    log "Set Environment Variable '$env_name'"

    if [ ! -d /etc/xinit/env.d/ ]; then
        mkdir -p /etc/xinit/env.d/
    fi

    echo "$env_value" >"/etc/xinit/env.d/$env_name"
    declare -gx "$env_name=$env_value"
}
